corelib/include/rtabmap/core/Odometry.h, corelib/include/rtabmap/core/OdometryF2F.h, corelib/include/rtabmap/core/OdometryF2M.h
Use virtual function to quickly determine what type of class is, so to avoid using dynamic cast which may slower run-time performance
=> added the type virtual function to avoid dynamic cast

corelib/src/CameraRGBD.cpp
I added 2 modification to improve the Freenect2 performance and fixed the color issue in TegraJPEG.
1. Added Freenect2 cuda pipeline.
2. Fixed TegraJPEG Color problem, convert from RGB to BGR.
I have already tested the code in Nvidia TX1.
=> Improve Freenect2 performance

corelib/include/rtabmap/core/FlannIndex.h
Had a bug while building about list not in std, fixed by just add it into the header file.
In file included from /home/zeng/essential/rtabmap/corelib/src/FlannIndex.cpp:28:0:
/home/zeng/essential/rtabmap/corelib/src/../include/rtabmap/core/FlannIndex.h:109:2: error: ‘list’ in namespace ‘std’ does not name a type
std::list<int> removedIndexes_;
^
/home/zeng/essential/rtabmap/corelib/src/FlannIndex.cpp: In member function ‘void rtabmap::FlannIndex::release()’:
/home/zeng/essential/rtabmap/corelib/src/FlannIndex.cpp:77:2: error: ‘removedIndexes_’ was not declared in this scope
removedIndexes_.clear();
^
In file included from /home/zeng/essential/rtabmap/corelib/src/FlannIndex.cpp:29:0:
/home/zeng/essential/rtabmap/corelib/src/FlannIndex.cpp: In member function ‘unsigned int …
=> include list in FlannIndex.h

corelib/src/Transform.cpp
I had problem with << operator on Transform - it writes to std::cout instead of given ostream os:
```
std::ostream& operator<<(std::ostream& os, const Transform& s)
{
for(int i = 0; i < 3; ++i)
{
for(int j = 0; j < 4; ++j)
{
std::cout << std::left << std::setw(12) << s.data()[i*4 + j];
}
std::cout << std::endl;
}
return os;
}
```
This commit just replaces std::cout with os:
```
std::ostream& operator<<(std::ostream& os, const Transform& s)
{
for(int i = 0; i < 3; ++i)
{
for(int j = 0; j < 4; ++j)
{
os << std::left << std::setw(12) << s.data()[i*4 + j];
}
os << std::endl;
}
return os;
}
```
=> Fix bug with ostream operator<< for Transform

corelib/src/Transform.cpp
Another problem with ostream operator <<  for Transform - missing space between numbers:
```
1           1.38778e-17 -8.32667e-17-4.44089e-16
4.16334e-17 1           5.55112e-17 -6.59195e-17
-2.77556e-173.33067e-16 1           5.55112e-17 
```
Commit just adds space after each number.
=> Fix missing space in ostream operator <<  for Transform

corelib/include/rtabmap/core/CameraStereo.h, corelib/src/CameraStereo.cpp
ZED SDK version is 2.0 now.(https://www.stereolabs.com/developers/)
So I want to use 2.0. 
It seems works well for me (Ubuntu 16.04).
There may be better solution in following 2 implementations. Anyway it works.
-slMat3cvMat  in line 939
-for loop in line 1016
=> change for zed sdk 2.0

corelib/src/Features2d.cpp
KAZE feature detector does not load custom feature params (min/max depth, ROI, etc).
=> KAZE - fix loading custom feature params

corelib/include/rtabmap/core/Rtabmap.h
Proper closing of name space with in the #RTABMAP_H_. Multiple includes of "Rtabmap.h" with in the component causing the compilation problem.
=> Proper closing of name space with in the #RTABMAP_H_

corelib/include/rtabmap/core/optimizer/OptimizerG2O.h, corelib/src/Graph.cpp, corelib/src/Rtabmap.cpp, corelib/src/RtabmapThread.cpp, corelib/src/optimizer/OptimizerG2O.cpp, guilib/src/MainWindow.cpp
Example output:
```
VERTEX_SE3:QUAT 1 0,000000 0,000000 0,000000 0,000000 0,000000 0,000000 1,000000
VERTEX_SE3:QUAT 2 0,112524 0,038664 -0,025436 0,001983 -0,006612 -0,012497 0,999898
VERTEX_SE3:QUAT 3 0,313028 0,038871 -0,004064 0,000580 -0,022157 -0,052914 0,998353
VERTEX_SE3:QUAT 4 0,691982 0,088411 -0,001627 -0,002716 -0,033791 -0,083035 0,995970
VERTEX_SE3:QUAT 5 1,013601 -0,189041 0,049828 0,016686 -0,054574 -0,104502 0,992886
VERTEX_SE3:QUAT 6 1,164547 -0,503220 0,228954 -0,001653 -0,092491 -0,185328 0,978313
VERTEX_SE3:QUAT 7 1,236641 -0,884730 0,395330 0,018900 -0,146133 -0,270647 0,951335
VERTEX_SE3:QUAT 8 1,383371 -1,178732 0,428721 -0,020164 -0,157695 -0,342753 0,925876
VERTEX_SE3:QUAT 9 1,563701 -1,296772 0,486302 -0,010725 -0,192911 -0,367471 0,909745
VERTEX_SE3:QUAT 10 …
```
=> OptmizerG2O: add prior edge export

tools/Export/main.cpp
Added a parameter in rtabmap-export to filter ceiling if wanted.
=> Add ceiling filter to rtabmap-export

package.xml
I kept the comments. 
Seems like `libopenni2-dev` is available on all platforms these days?
=> List dependencies only once

docker/focal/Dockerfile
Fix K4A binary download step in focal dockerfile failure due to missing curl install. Curl could be added earlier in the dockerfile but thought it best to keep the scope of the fix local to the install of k4a so as not to affect eailier build steps cache.
=> fix missing curl install in focal dockerfile

corelib/include/rtabmap/core/camera/CameraDepthAI.h, corelib/src/camera/CameraDepthAI.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
Add option to enable IR laser dot projector (active stereo) and IR illumination LED (for night-vision).
The default value for laser dot projector is 0 (turn off). Because the projected pattern is good for depth estimation but may harm feature extraction.
It looks like there are other issues with DepthAI integration. I'll try to troubleshoot and fix them soon.
=> Update DepthAI Integration

guilib/include/rtabmap/gui/ExportCloudsDialog.h, guilib/src/ExportCloudsDialog.cpp
PCL 1.13.0 introduced tex_coord_indices in pcl::TextureMesh. Omitting to fill the new vector causes a segmentation fault. The pull request fixes this issue and makes exporting textured meshes possible again.
=> fixes for texture mesh export for pcl > 1.13.0

corelib/include/rtabmap/core/camera/CameraDepthAI.h, corelib/src/camera/CameraDepthAI.cpp, corelib/src/util3d.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
Fix #1036 
This makes better use of the FOV of wide-angle lens.
=> Support cameras with different fx and fy, enable alphaScaling for OAK cameras

corelib/include/rtabmap/core/camera/CameraDepthAI.h, corelib/src/camera/CameraDepthAI.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
Hi, I added on-device GFTT feature according to your note. I'll try to add SuperPoint later. So later for `detectFeatures_`, 0 is None, 1 is GFTT, 2 is SuperPoint. Or change it to enum afterwards.
There are some differences between DepthAI and OpenCV in the implementation of GFTT. I'm trying to reuse parameters set in other panels, which might be a little awkward. Maybe you have a better way. I tried many parameters, mainly to increase the number of features. DepthAI first uses CornerDetector to detect corner points, and then uses FeatureMaintainer to filter out some. So when `numTargetFeatures` is set to 320 by default, it may only return more than 200 points in the end. This can make rtabmap less stable. Regarding the actual `numMaxFeatures`, the …
=> add depthai gftt detector

package.xml
There is no dependency in this package on qt_gui_cpp. Instead, just use a dependency on qtbase5-dev
=> Remove dependency on qt_gui_cpp.

corelib/include/rtabmap/core/camera/CameraDepthAI.h, corelib/src/camera/CameraDepthAI.cpp
I have received OAK-D Pro W PoE. Its IMU local transform is easy to determine, it has the same orientation as the USB model, but with a different offset. What is more troublesome is the communication bandwidth. I couldn't get enough camera frame rate and IMU frame rate with the previous configuration. The official documentation says a lot about this. I'll have to see what tuning needs to be done.
In addition, the previous USB models equipped with BMI270 also have [IMU frame rate problems](https://github.com/luxonis/depthai-ros/issues/145). Certain algorithms may be affected.
=> OAK-D PoE Update

CMakeLists.txt, corelib/src/odometry/OdometryMSCKF.cpp
Now msckf_vio is ready to use. Tested with OAK cameras. You can refer to [this patch](https://gist.github.com/borongyuan/90f10aa6969ebccdba2b19ce0cfa77ea) or [my fork](https://github.com/borongyuan/msckf_vio) for changes. I made some changes to the initial frame. Now the body frame and IMU frame have the same reference frame, avoiding the inconvenience of https://github.com/KumarRobotics/msckf_vio/issues/39#issuecomment-398562078. After initialization, the body frame is located at the origin of the world frame, and its orientation is aligned with gravity. This is consistent with the initialization of the odometry of RTAB-Map. Some of the previous hardcoded parameters seem to be for the euroc dataset. After modification it should be suitable for other hardwares.
=> MSCKF_VIO Update

tools/EurocDataset/CMakeLists.txt
When packaging yaml-cpp 0.8.0 on vcpkg, there were build issues with rtabmap.
Notably, the debug build fails due to `LIBRARIES` having `yaml-cpp` hardcoded, while yaml-cpp has a debug postfix. This, in combination with 0.8.0 renaming the target to `yaml-cpp::yaml-cpp` means that `yaml-cpp` is treated as a literal library name.
This PR updates the find logic to address these issues:
- For the include directories, the variable name used upstream is [`YAML_CPP_INCLUDE_DIR`](https://github.com/jbeder/yaml-cpp/blob/f7320141120f720aecc4c32be25586e7da9eb978/yaml-cpp-config.cmake.in#L10).
- The target name in 0.8.0 changed to `yaml-cpp::yaml-cpp`, but the variable `YAML_CPP_LIBRARIES` was not updated. This issue has already been reported upstream, but when this specific version of yaml-cpp is …
=> CMake: Add compatibility for yaml-cpp 0.8.0.

corelib/src/camera/CameraDepthAI.cpp
The kernel size of census transform is set to AUTO by default. Looks like CT-7x7 is used at 800p. I found that CT-7x9 gives better depth quality for both 800p and 400p. Don't know why it is not used as default.
IMU rate is set to 100 Hz as none of the devices with BMI270 can reach 200 Hz. PoE models can go up to around 120 Hz. It works well when using msckf_vio. Feature noise is best reduced to 0.02 to avoid drift.
Msckf_vio may not be the most accurate VIO, but it is certainly robust. I often encounter drift issues when using OpenVINS, and I am still looking for the cause.
=> Update OAK stereo config and IMU rate

CMakeLists.txt, corelib/src/CMakeLists.txt
When link to libpointmatcher master(https://github.com/ethz-asl/libpointmatcher) with libnabo master (https://github.com/ethz-asl/libnabo) compiler failed:  
Undefined symbols for architecture x86_64:
"Nabo::NearestNeighbourSearch<double, Eigen::Matrix<double, -1, -1, 0, -1, -1> >::create(Eigen::Matrix<double, -1, -1, 0, -1, -1> const&, int, Nabo::NearestNeighbourSearch<double, Eigen::Matrix<double, -1, -1, 0, -1, -1> >::SearchType, unsigned int, ...
related to https://github.com/ethz-asl/libpointmatcher/issues/514 
and I employ a fix from https://github.com/ethz-asl/libpointmatcher/pull/513 to fix this error.
=> fix for Undefined symbols for architecture x86_64: "Nabo::NearestNeighbourSearch<double... when link to libpointmatcher

corelib/include/rtabmap/core/CameraInfo.h, corelib/include/rtabmap/core/CameraThread.h, corelib/src/CameraThread.cpp, guilib/include/rtabmap/gui/PreferencesDialog.h, guilib/src/MainWindow.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui, tools/DataRecorder/main.cpp, tools/EurocDataset/main.cpp, tools/KittiDataset/main.cpp, tools/RgbdDataset/main.cpp
Both OpenVINS and ORB-SLAM3 have histogram equalization methods. ORB-SLAM3 says that it is mainly for TUM-VI dataset. When I used the OAK camera for outdoor testing, I found that the contrast of the original images is actually low. The SLAM performance is improved after applying histogram equalization.
=> Add Histogram Equalization

corelib/include/rtabmap/core/Parameters.h, corelib/include/rtabmap/core/odometry/OdometryOpenVINS.h, corelib/src/odometry/OdometryOpenVINS.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
Now this can be used with stereo camera or rgbd camera (mono mode). The implementation of OpenVINS looks better than msckf_vio. Now this is ready for review and test. The dynamic initialization part is not enabled yet. Some updates will be added later.
=> OpenVINS Update

corelib/src/odometry/OdometryOpenVINS.cpp
Add openvins msckf features as outliers for visualization. However, msckf features are not entirely outliers. They are actually lost features + long-term features not used in updaterSLAM + short-term features. They are used in updaterMSCKF.
https://github.com/rpng/open_vins/blob/4534a2f32d4763bdc8c95121b3292c7423e12aca/ov_msckf/src/core/VioManager.cpp#L497-L500
Fill localMap with active tracked features. Active tracked features are more numerous and have corresponding IDs. We can see how they are triangulated.
=> Update odometry info of OpenVINS

corelib/include/rtabmap/core/camera/CameraDepthAI.h, corelib/src/camera/CameraDepthAI.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
Fix distortion correction problem of small FOV devices.
I have been testing with wide FOV devices before. When I tried OAK-D S2 today I found that it didn't work at all. I checked [the doc](https://docs.luxonis.com/projects/api/en/latest/references/cpp/#_CPPv4N3dai21StereoDepthProperties26useHomographyRectificationE) and found that the default configuration does not perform distortion correction on small FOV devices. I can't understand why they do this. We need to force distortion correction on all devices.
Remove deprecated IMU firmware update API.
enableFirmwareUpdate() is deprecated since https://github.com/luxonis/depthai-core/commit/12b198a67f9c7a56747666679f00763c35cf64e3. I don't feel the need to deal with firmware updates here. Most devices don't need to be updated. Or the user …
=> OAK bug fixes and improvements

corelib/include/rtabmap/core/Parameters.h, corelib/include/rtabmap/core/odometry/OdometryOpenVINS.h, corelib/src/Odometry.cpp, corelib/src/odometry/OdometryOpenVINS.cpp, guilib/include/rtabmap/gui/PreferencesDialog.h, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
Hi, @matlabbe
I added more OpenVINS params. Enabling online calibration sometimes improves accuracy, but may also hurt the performance due to degenerate motions. You can refer to the conclusion of [this video](https://www.youtube.com/watch?v=uf367hP6s3M). Dynamic initialization may be useful for odom reset. Even if it is enabled, the system will try static initialization first. There are also several feature initializer params which may need to be tuned in outdoor scenes.
There’s no need to merge this PR right away. There is another important issue to resolve. We are not using covariance properly. When I was testing in some large scenes recently, I found that after successful loop closure, some neighbor links would be stretched extremely long. And VIO has been working correctly, so I …
=> Supplement and Adjust OpenVINS Parameters

corelib/src/Features2d.cpp, corelib/src/Memory.cpp
filterKeypointsByDepth is missing in this if-branch
=> Add missing filterKeypointsByDepth step

corelib/include/rtabmap/core/Parameters.h, corelib/include/rtabmap/core/Rtabmap.h, corelib/src/Rtabmap.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
Removed landmarks from the fixed priors (https://github.com/introlab/rtabmap_ros/issues/1057)
=> Tuning localization priors (added RGBD/LocalizationPriorError parameter)

corelib/src/camera/CameraDepthAI.cpp
In some network topologies PoE cameras cannot be discovered using getAllAvailableDevices(). But if their IPs are manually specified, they are actually accessible. This fix allows us to use these cameras. But there are still some small problems. For example, we cannot guarantee that the PoE camera is actually found before dai::Device is initialized. This is because there is only getDeviceByMxId() in the API, but not getDeviceByName(). Before dai::Device is initialized, its protocol cannot be detected.
=> fix protocol detection for undiscoverable devices

corelib/include/rtabmap/core/Parameters.h, corelib/src/odometry/OdometryOpenVINS.cpp, guilib/src/ui/preferencesDialog.ui
When ZUPT is enabled, OpenVINS is initialized statically. However, the initialization flag of ov_msckf::VioManager will only become true after there is initial motion excitation. Therefore, RTAB-Map would not receive the data until the camera moved. After the fix, the system can get data earlier, while remaining stationary.
Pixel noise is restored to 1. If cameras and IMU are not perfectly synchronized, it may result in fewer feature points. At this time, online offset calibration should be enabled rather than increasing pixel noise. See #1151.
=> start outputting data after static initialization

corelib/src/util2d.cpp
This fixes the problem of extracting multiple keypoints at the same location. Previously, where prob is greater than the threshold were extracted as keypoints.
https://github.com/introlab/rtabmap/blob/7ab1ee0a0b12dd8d5f607c5cf536505b5d0d7779/corelib/src/camera/CameraDepthAI.cpp#L653
https://github.com/introlab/rtabmap/blob/7ab1ee0a0b12dd8d5f607c5cf536505b5d0d7779/corelib/src/superpoint_torch/SuperPoint.cc#L161
Therefore in NMS, local maximums are found first, and then neighbors are suppressed. Now for loop closure, it works fine when the image resolution is 400P or 800P. For odometry, 800P is not suitable for F2M, but is suitable for F2F. Because the position of keypoints is more jittery.
=> improve NMS implementation

corelib/include/rtabmap/core/camera/CameraDepthAI.h, corelib/src/camera/CameraDepthAI.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
I added RGBD mode for OAK cameras, but only those models with global shutter color cameras are supported. There are actually only 2 models in the [supported sensors](https://docs.luxonis.com/projects/hardware/en/latest/pages/articles/supported_sensors/) list, [OV9782](https://docs.luxonis.com/projects/hardware/en/latest/pages/articles/sensors/ov9782/) and [AR0234](https://docs.luxonis.com/projects/hardware/en/latest/pages/articles/sensors/ar0234/). Their resolutions happen to be consistent with the mono camera's resolution list, so adding list items can be avoided. I'm using [OAK-D Pro W Dev](https://shop.luxonis.com/products/oak-d-pro-w-dev), so I added the NG2094 board. As for AR0234, it is currently only used in OAK-D LR and needs to be tested and updated later.
Some adjustments have …
=> Add RGBD mode for OAK camera

corelib/src/camera/CameraDepthAI.cpp
This borrows from the PyTorch implementation in SuperGlue, but uses this [corrected version](https://github.com/magicleap/SuperGluePretrainedNetwork/issues/112#issuecomment-1199862202). This implementation is relatively simple, and since OpenCV has various optimizations for morphological operations, it will theoretically have better performance. But I haven't done any performance comparison testing yet. Since this is performed on heatmap, the NMS in SuperPoint Torch can be changed to PyTorch implementation. This way we can remove this part from util2d and introduce ANMS later.
=> Reimplement NMS using morphological operations

corelib/src/CameraThread.cpp
Add support for histogram equalization of color images. Color images are first converted to YCrCb color space, and histogram equalization is performed only on the Y channel.
Why use YCrCb instead of HSV or LAB?
They should have similar results. But according to [OpenCV's color conversion documentation](https://docs.opencv.org/4.x/de/d25/imgproc_color_conversions.html), the Y channel of BGR2YCrCb is calculated in the same way as BGR2GRAY. Therefore, it can ensure the same effect as converting to gray image first and then performing histogram equalization.
=> support color histogram equalization

corelib/src/Features2d.cpp
This only happens with SuperPoint. Rtabmap will limit key points if exceeds the limit set by Kp/MaxFeatures THEN it will generate descriptors based on extracted key points. It will work classic Features Extraction method. However, SuperPoint will generate key points and descriptors at the same time, if the limit key points method calls inside the extract key point method it will lead to a mismatched number of key points and descriptors later when the generate descriptor method calls. It is solved by ignoring the limit key points method inside the generate key point method and only limiting key points after generating the descriptors if necessary.
=> not limitKps inside Feature2D::generateKeypoints when using pyDetector

corelib/include/rtabmap/core/camera/CameraDepthAI.h, corelib/src/DBDriverSqlite3.cpp, corelib/src/camera/CameraDepthAI.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
All messages except IMU are synchronized using the Sync node introduced in [v2.24.0](https://github.com/luxonis/depthai-core/releases/tag/v2.24.0). LGTM, but I'll keep this PR as a draft until the depthai in ROS repo is updated to 2.24.0. In addition, they have not added doc for Sync node yet, only providing new examples. We can do more inspections and tests during this time.
The IR settings have also been changed to new methods in v2.24.0.
=> OAK Internal Sync & DepthAI HF-Net Support

corelib/src/camera/CameraDepthAI.cpp
The inference is correct using HF-Net blob file. I made a silly mistake when converting to cv::Mat. This solves https://github.com/introlab/rtabmap/issues/1215#issuecomment-2002006330. Now I can get similar results to https://github.com/introlab/rtabmap/issues/1105#issuecomment-2031099209 in online testing.
=> copy global descriptor

corelib/src/Rtabmap.cpp
I constructed a new method to adjust the likelihood, as a solution to https://github.com/introlab/rtabmap/issues/1105#issuecomment-2031099209. It should be compatible with previous similarity evaluation methods, as well as VLAD. The idea is to calculate z-score for values ​​greater than μ + σ. This eliminates the effect of different distributions. For new location likelihood, how significant the max value is will be evaluated.
=> adjust likelihood using z-score

guilib/include/rtabmap/gui/DatabaseViewer.h, guilib/include/rtabmap/gui/GraphViewer.h, guilib/src/DatabaseViewer.cpp, guilib/src/GraphViewer.cpp, guilib/src/ui/DatabaseViewer.ui
I added the ability to mouse click on nodes and links in the graph view and have them populate slider_A and slider_B in the main view window.
=> Clicking Nodes\Links brings them up in viewer

app/ios/RTABMapApp/install_deps.sh
Hi, I tried building the ios demo application and install_deps.sh was failing while trying to build PCL.
CMake was failing to produce XCode project because the check for SSE support was failing. I removed it, since as far as I know, it's not required for aarch64 builds.
Project builds nicely after updating the script.
=> Update iOS app's install_deps.sh to remove PCL's SSE dependency

corelib/include/rtabmap/core/Features2d.h, corelib/include/rtabmap/core/util2d.h, corelib/src/Features2d.cpp, corelib/src/util2d.cpp
I missed an important step. In ANMS, keypoints need to be sorted by strength first. When calling util2d::SSC(), keypoints can now be sorted, or an additional sorted indx can be used.
=> Sort keypoints before SSC

corelib/include/rtabmap/core/camera/CameraStereoVideo.h, corelib/include/rtabmap/core/camera/CameraVideo.h, corelib/src/camera/CameraStereoVideo.cpp, corelib/src/camera/CameraVideo.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
Related posts from [nesquik011](https://github.com/nesquik011):
* http://official-rtab-map-forum.206.s1.nabble.com/stereo-example-td10512i20.html
* https://github.com/introlab/rtabmap/issues/1353
* https://github.com/introlab/rtabmap/issues/1352
=> Adding FOURCC usb camera support

guilib/src/MainWindow.cpp
Previously, the loop threshold was drawn in the posterior plot. But I don't understand how to compare it with the posterior curve. What we can compare directly is the virtual place hypothesis and "1 - loop threshold". These changes only affect the plot.
=> Draw "1 - Loop Thr" along with posterior

corelib/include/rtabmap/core/Features2d.h, corelib/include/rtabmap/core/Memory.h, corelib/include/rtabmap/core/Parameters.h, corelib/include/rtabmap/core/RegistrationVis.h, corelib/include/rtabmap/core/util3d.h, corelib/src/Features2d.cpp, corelib/src/Memory.cpp, corelib/src/RegistrationVis.cpp, corelib/src/util3d.cpp, guilib/src/ParametersToolBox.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
Added options `Mem/DepthMaskFloorThr` and `Vis/DepthMaskFloorThr`. When enabled, features will be extracted only on objects over the specified threshold. If the threshold is negative, the inverse is done (i.e., extracting features only on the floor).
Also enabled CudaSIFT to use depth mask.
=> Added floor filtering options for features extraction

corelib/src/optimizer/OptimizerCeres.cpp, corelib/src/optimizer/ceres/pose_graph_2d/angle_manifold.h, corelib/src/optimizer/ceres/pose_graph_3d/eigen_quaternion_parameterization.h
Ceres 2.1+ introduces "manifolds" in replacement of "local parameterizations". This PR supports manifolds in a backwards-compatible way, such that rtabmap can be compiled with both Ceres 2.1+ or older.
=> Support Ceres 2.1+ Manifolds in backwards-compatible manner

corelib/include/rtabmap/core/DBDriver.h, corelib/include/rtabmap/core/DBDriverSqlite3.h, corelib/include/rtabmap/core/util3d_surface.h, corelib/src/DBDriver.cpp, corelib/src/DBDriverSqlite3.cpp, corelib/src/util3d_surface.cpp, guilib/src/ExportCloudsDialog.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/exportCloudsDialog.ui, tools/Export/main.cpp
Refactoring:
* https://github.com/introlab/rtabmap/issues/1368
* https://github.com/introlab/rtabmap/issues/1375
New options:
```
--opt #               Optimization approach:
0=Iterative Global Optimization (default)
1=Full Global Optimization
2=Use optimized poses already computed in the database instead
of re-computing them (fallback to default if optimized poses don't exist).
3=No optimization, use odometry poses directly.
--density_radius #    Filter poses in a fixed radius (m) to keep only one to be exported in the assembled cloud.
--density_angle #     Filter poses up to angle (deg) in the --density_radius.
```
Example the export a large map in multiple files.
1. Make sure the database has optimized poses saved in the database with:
```
rtabmap-export --poses --save_in_db rtabmap.db …
```
=> Export tool memory optimization

corelib/include/rtabmap/core/Compression.h, corelib/include/rtabmap/core/DBDriver.h, corelib/include/rtabmap/core/DBDriverSqlite3.h, corelib/include/rtabmap/core/Memory.h, corelib/include/rtabmap/core/Parameters.h, corelib/include/rtabmap/core/rvl_codec.h, corelib/src/CMakeLists.txt, corelib/src/Compression.cpp, corelib/src/DBDriver.cpp, corelib/src/DBDriverSqlite3.cpp, corelib/src/Memory.cpp, corelib/src/camera/CameraStereoZed.cpp, corelib/src/rvl_codec.cpp, guilib/src/DatabaseViewer.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
=> add support for RVL depth image compression

corelib/src/optimizer/ceres/pose_graph_2d/angle_manifold.h
Related to #1405
corelib/src/optimizer/ceres/pose_graph_3d/eigen_quaternion_parameterization.h is also not compatible. However this file is not used, so I left it as is.
=> fix build with ceres<2.1

guilib/src/PreferencesDialog.cpp
setting RTABMAP_ORB_SLAM true would put the if statements all out of whack in the perferences dialog:
`/home/grover/vision_dev/rtabmap/guilib/src/PreferencesDialog.cpp: In member function ‘void rtabmap::PreferencesDialog::setParameter(const string&, const string&)’:
/home/grover/vision_dev/rtabmap/guilib/src/PreferencesDialog.cpp:4904:7: error: expected ‘}’ before ‘else’
4904 |       else
|       ^~~~
/home/grover/vision_dev/rtabmap/guilib/src/PreferencesDialog.cpp:4894:6: note: to match this ‘{’
4894 |      {
|      ^
`
There may be a cleaner way to do it, but his fixed my build
=> fixed ORB_SLAM preproc breaking gui conditionals

corelib/include/rtabmap/core/camera/CameraDepthAI.h, corelib/src/camera/CameraDepthAI.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
Hi, we have some new improvements for DepthAI integration. This includes reorganizing parameters and code structure, performing advanced tuning on the SGBM pipeline, and adding support for more OAK models. These improvements will be committed and explained in the coming days.
=> Further improvements to DepthAI integration

corelib/include/rtabmap/core/Parameters.h, corelib/include/rtabmap/core/odometry/OdometryF2M.h, corelib/src/odometry/OdometryF2M.cpp, guilib/src/PreferencesDialog.cpp, guilib/src/ui/preferencesDialog.ui
Added parameters:
* `OdomF2M/BundleUpdateFeatureMapOnAllFrames`: Update 3D local feature map on every frame with bundle adjustment. Recommended if `Vis/DepthAsMask=false` and `Mem/UseOdomFeatures=true` so that features without depth are better triangulated on every frame (not only on keyframes). If disabled, the feature map is updated only when a new keyframe is added (legacy approach).
* `OdomF2M/FloorThreshold`: Only track features in 3D feature map that are over this threshold (height in base frame). Can be useful to ignore reflections on the floor. 0 means disabled.
* `OdomF2M/InitDepthFactor`: Depth factor used to initialize depth of features without depth. Depth = Factor * fx.
TODO: Re-run vslam benchmark datasets with and without `OdomF2M/BundleUpdateFeatureMapOnAllFrames` to see …
=> Improved depth estimation of mono features

corelib/src/superpoint_torch/SuperPoint.cc
Fixes #1505. When SuperPoint detects exactly 1 feature for a photo, dimensions are collapsed and the application crashes  during the transpose operation at line 247.
=> Handle edge case when SuperPoint detects only 1 keypoint

corelib/src/camera/CameraDepthAI.cpp
OAK cameras released after the end of 2024 use a tilted sensor model during factory calibration. That is, the two additional parameters tauX and tauY are enabled. So we now need to use intrinsic with 14 parameters instead of 8. This will slightly change the result of cv::getOptimalNewCameraMatrix() and theoretically also slightly improve SLAM accuracy.
https://docs.luxonis.com/hardware/platform/depth/calibration/#About%20Camera%20Calibration-Distortion%20Models
We found that the OAK camera also had other accuracy issues, and it always overestimated the distance to distant objects. The explanation their team gave me was that due to the nonlinear nature of disparity estimation, even if the cameras are perfectly calibrated and rectified, the depth estimation will be biased. This analysis is …
=> Minor correction on using tilted sensor model for OAK camera
