corelib/src/CameraRGBD.cpp

Hello,
libfreenect2 has changed base API and it breaks current state of rtabmap.
I followed the same modification in the code-iai/iai_kinect2#189.
Thank you

Use new libfreenect2 API

---

CMakeLists.txt

new version of pcl has [been released](https://bugs.launchpad.net/ubuntu/+source/pcl/+bug/1704459) so this hack is not necessary anymore

remove hack now that upstream pcl has been rebuilt

---

corelib/src/CameraThread.cpp

Mathieu, unless I'm missing something, you intended to change this to isEmpty() correct?

Fix laserscan from depth

---

guilib/src/PreferencesDialog.cpp

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

PreferencesDialog: Add forgotten include

---

corelib/src/Memory.cpp
corelib/src/optimizer/OptimizerG2O.cpp

This addresses https://github.com/introlab/rtabmap/issues/345 and the suggestions for @matlabbe.
Requires some more testing.

Feature: add support for EDGE_XY and EDGE_XYZ priors

---

corelib/src/optimizer/OptimizerG2O.cpp

Fixes the reported in https://github.com/introlab/rtabmap/issues/345#issuecomment-451496826.
@matlabbe

EdgeSE3XYZPrior: add ParamOffset

---

corelib/src/camera/CameraRealSense2.cpp

fix the realsense release problem

fix the realsense release problem

---

corelib/include/rtabmap/core/camera/CameraStereoZed.h
corelib/src/camera/CameraStereoZed.cpp

Add support for Stereolabs ZED SDK v3.0 
Guaranteed compatibility with older SDK v2.x

Compatibility support for ZED SDK v3.0

---

tools/Report/main.cpp

To test : rtabmap-report --report $PATH

add option to create a report.csv file in /tools/Report

---

corelib/include/rtabmap/core/camera/CameraK4A.h
corelib/src/camera/CameraK4A.cpp
guilib/include/rtabmap/gui/MainWindow.h
guilib/src/MainWindow.cpp
guilib/src/ui/mainWindow.ui

In anticipation of Kinect for Azure device support

Added Kinect for Azure menu option

---

corelib/src/MarkerDetector.cpp

OpenCV 4.7 moved aruco, and has breaking changes. This PR adds situations for it.

OpenCV 4.7 moved aruco, and has breaking changes

---

corelib/src/odometry/OdometryORBSLAM.cpp

Fix RGBD with ORB SLAM

---

corelib/include/rtabmap/core/camera/CameraDepthAI.h
corelib/include/rtabmap/core/util2d.h
corelib/src/camera/CameraDepthAI.cpp
corelib/src/superpoint_torch/SuperPoint.cc
corelib/src/util2d.cpp
guilib/include/rtabmap/gui/PreferencesDialog.h
guilib/src/PreferencesDialog.cpp
guilib/src/ui/preferencesDialog.ui

SuperPoint MyriadX Blob:
https://github.com/borongyuan/depthai-superpoint/raw/main/blobs/superpoint_200x320_10shave.blob

Add Depthai SuperPoint

---

corelib/src/superpoint_torch/SuperPoint.cc

Successor of #1192 
I did't actually seen SuperPoint Torch perform very well on the Jetson Orin Nano if it's simply called through libtorch. After all, its FP32 computing power is not very good, only 1.28 TFLOPS. We may consider adding some optimizations later.

SuperPoint Torch Simple NMS

---

corelib/include/rtabmap/core/Features2d.h
corelib/include/rtabmap/core/Memory.h
corelib/include/rtabmap/core/Parameters.h
corelib/include/rtabmap/core/util2d.h
corelib/src/Features2d.cpp
corelib/src/Memory.cpp
corelib/src/RegistrationVis.cpp
corelib/src/SensorCaptureThread.cpp
corelib/src/util2d.cpp
guilib/src/DatabaseViewer.cpp
guilib/src/PreferencesDialog.cpp
guilib/src/ui/preferencesDialog.ui

Hi,
I added ANMS as discussed in #1127. Only SSC method is provided. Because it is the best performing approximation method and does not rely on tree data structure. Therefore we do not need to add nanoflann support for the time being.

Add ANMS (SSC method)

---

CMakeLists.txt
RTABMapConfig.cmake.in
guilib/include/rtabmap/gui/CalibrationDialog.h
guilib/src/CalibrationDialog.cpp

Original issue: https://github.com/introlab/rtabmap_ros/issues/1200

Fixing ChArUco board support on opencv >= 4.7.0

---

corelib/src/SensorCaptureThread.cpp

See https://github.com/introlab/rtabmap/issues/1388
Contributor: [4jakers18](https://github.com/4jakers18)

Applying suggestion of #1388

---

corelib/src/camera/CameraDepthAI.cpp

If the neural network does not detect any features, `cv::remap(coarse_desc, descriptors, map1, map2, cv::INTER_LINEAR);` will crash because map1 and map2 are empty.
This may happen when the camera is completely blocked or when the image becomes completely black or white due to a sudden change in lighting.

Fixed cv::remap() crach when the neural network did not detect any features

---

corelib/src/optimizer/OptimizerCeres.cpp

Fixed the typo in corelib/src/optimizer/OptimizerCeres.cpp#L200

Remove typo in ceres optimizer branch

---

guilib/include/rtabmap/gui/CloudViewer.h
guilib/include/rtabmap/gui/ImageView.h
guilib/include/rtabmap/gui/PointCloudColorHandlerIntensityField.h
guilib/include/rtabmap/gui/PointCloudColorHandlerMinMaxGenericField.h
guilib/include/rtabmap/utilite/UCv2Qt.h
guilib/src/CloudViewer.cpp
guilib/src/DatabaseViewer.cpp
guilib/src/ImageView.cpp

Also, add option to set min/max color scale on point clouds in CloudViewer.
Todo:

ImageView: Depth color map in base frame
